FROM php:8.3-fpm-alpine

RUN apk add --no-cache icu-dev $PHPIZE_DEPS \
    && docker-php-ext-install intl pdo_mysql opcache

COPY docker/php/php.ini /usr/local/etc/php/conf.d/app.ini

WORKDIR /var/www/html

EXPOSE 9000
CMD ["php-fpm", "-F"]