apiVersion: v1
kind: Service
metadata:
  name: httpbin-nodeport
  namespace: httpbin-test
spec:
  type: NodePort
  selector:
    app: httpbin
  ports:
    - port: 80          # port interne du service
      targetPort: 80    # port exposé dans le container
      protocol: TCP
      nodePort: 30080   # port sur lequel le service sera accessible (30000–32767). Facultatif : K8s choisit un port si vous ne le mettez pas.
